package data_sources

import (
	"context"
	"terraform-provider-edgio/internal/edgio_api"
	"terraform-provider-edgio/internal/edgio_provider/models"
	"terraform-provider-edgio/internal/edgio_provider/utility"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TlsCertsDataSource struct {
	client edgio_api.EdgioClientInterface
}

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource = &TlsCertsDataSource{}
)

func NewTlsCertsDataSource(client edgio_api.EdgioClientInterface) *TlsCertsDataSource {
	return &TlsCertsDataSource{
		client: client,
	}
}

func (d *TlsCertsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "edgio_tls_certs"
}

func (d *TlsCertsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"environment_id": schema.StringAttribute{
				Required:    true,
				Description: `The environment ID to filter the TLS certificates.`,
			},
			"item_count": schema.Int32Attribute{
				Computed:    true,
				Description: `The total number of TLS certificates to load.`,
			},
			"certificates": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:    true,
							Description: "The TLS certificate's system-defined ID.",
						},
						"environment_id": schema.StringAttribute{
							Computed:    true,
							Description: "The environment ID associated with the certificate.",
						},
						"primary_cert": schema.StringAttribute{
							Computed:    true,
							Description: "The primary TLS certificate.",
						},
						"intermediate_cert": schema.StringAttribute{
							Computed:    true,
							Description: "The intermediate TLS certificate, if available.",
						},
						"expiration": schema.StringAttribute{
							Computed:    true,
							Description: "The expiration date of the TLS certificate (in UTC).",
						},
						"status": schema.StringAttribute{
							Computed:    true,
							Description: `The status of the TLS certificate: created, activating, activated, failed, expired.`,
						},
						"generated": schema.BoolAttribute{
							Computed:    true,
							Description: "Whether the TLS certificate was generated by Edgio.",
						},
						"serial": schema.StringAttribute{
							Computed:    true,
							Description: "The serial number of the TLS certificate.",
						},
						"common_name": schema.StringAttribute{
							Computed:    true,
							Description: "The common name (CN) of the TLS certificate.",
						},
						"alternative_names": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
							Description: "The Subject Alternative Names (SAN) of the TLS certificate.",
						},
						"activation_error": schema.StringAttribute{
							Computed:    true,
							Description: "Error message if the TLS certificate could not be activated.",
						},
						"created_at": schema.StringAttribute{
							Computed:    true,
							Description: "The creation date and time of the TLS certificate (UTC).",
						},
						"updated_at": schema.StringAttribute{
							Computed:    true,
							Description: "The last modification date and time of the TLS certificate (UTC).",
						},
					},
				},
			},
		},
	}
}

func (d *TlsCertsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var environmentID string
	var item_count int32
	diags := req.Config.GetAttribute(ctx, path.Root("environment_id"), &environmentID)
	resp.Diagnostics.Append(diags...)
	req.Config.GetAttribute(ctx, path.Root("item_count"), &item_count)

	if resp.Diagnostics.HasError() {
		return
	}

	tlsCertsResponse, err := d.client.GetTlsCerts(0, int(item_count), environmentID)
	if err != nil {
		resp.Diagnostics.AddError("Error reading TLS certificates", err.Error())
		return
	}

	state := models.TLSCertsModel{
		EnvironmentID: types.StringValue(environmentID),
		ItemCount:     types.Int32Value(tlsCertsResponse.TotalItems),
		Certificates:  []models.TLSCertModel{},
	}

	for _, cert := range tlsCertsResponse.Certificates {
		certState := utility.ConvertTlsCertsToModel(&cert)
		state.Certificates = append(state.Certificates, certState)
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}
