package data_sources

import (
	"context"
	"terraform-provider-edgio/internal/edgio_api"
	"terraform-provider-edgio/internal/edgio_provider/models"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TlsCertsDataSource struct {
	client *edgio_api.EdgioClient
}

// Ensure the implementation satisfies the expected interfaces.
var (
	_ datasource.DataSource = &TlsCertsDataSource{}
)

func NewTlsCertsDataSource(client *edgio_api.EdgioClient) *TlsCertsDataSource {
	return &TlsCertsDataSource{
		client: client,
	}
}

func (d *TlsCertsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = "edgio_tls_certs"
}

func (d *TlsCertsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"environment_id": schema.StringAttribute{
				Required:    true,
				Description: `The environment ID to filter the TLS certificates.`,
			},
			"page": schema.Int32Attribute{
				Optional:    true,
				Description: `The page number to fetch.`,
			},
			"page_size": schema.Int32Attribute{
				Optional:    true,
				Description: `The number of items per page.`,
			},
			"item_count": schema.Int32Attribute{
				Computed:    true,
				Description: `The total number of TLS certificates.`,
			},
			"certificates": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:    true,
							Description: "The TLS certificate's system-defined ID.",
						},
						"environment_id": schema.StringAttribute{
							Computed:    true,
							Description: "The environment ID associated with the certificate.",
						},
						"primary_cert": schema.StringAttribute{
							Computed:    true,
							Description: "The primary TLS certificate.",
						},
						"intermediate_cert": schema.StringAttribute{
							Computed:    true,
							Description: "The intermediate TLS certificate, if available.",
						},
						"expiration": schema.StringAttribute{
							Computed:    true,
							Description: "The expiration date of the TLS certificate (in UTC).",
						},
						"status": schema.StringAttribute{
							Computed:    true,
							Description: `The status of the TLS certificate: created, activating, activated, failed, expired.`,
						},
						"generated": schema.BoolAttribute{
							Computed:    true,
							Description: "Whether the TLS certificate was generated by Edgio.",
						},
						"serial": schema.StringAttribute{
							Computed:    true,
							Description: "The serial number of the TLS certificate.",
						},
						"common_name": schema.StringAttribute{
							Computed:    true,
							Description: "The common name (CN) of the TLS certificate.",
						},
						"alternative_names": schema.ListAttribute{
							Computed:    true,
							ElementType: types.StringType,
							Description: "The Subject Alternative Names (SAN) of the TLS certificate.",
						},
						"activation_error": schema.StringAttribute{
							Computed:    true,
							Description: "Error message if the TLS certificate could not be activated.",
						},
						"created_at": schema.StringAttribute{
							Computed:    true,
							Description: "The creation date and time of the TLS certificate (UTC).",
						},
						"updated_at": schema.StringAttribute{
							Computed:    true,
							Description: "The last modification date and time of the TLS certificate (UTC).",
						},
					},
				},
			},
		},
	}
}

func (d *TlsCertsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var environmentID string
	var page int32
	var pageSize int32
	diags := req.Config.GetAttribute(ctx, path.Root("environment_id"), &environmentID)
	resp.Diagnostics.Append(diags...)
	req.Config.GetAttribute(ctx, path.Root("page"), &page)
	req.Config.GetAttribute(ctx, path.Root("page_size"), &pageSize)

	if resp.Diagnostics.HasError() {
		return
	}

	tlsCertsResponse, err := d.client.GetTlsCerts(int(page), int(pageSize), environmentID)
	if err != nil {
		resp.Diagnostics.AddError("Error reading TLS certificates", err.Error())
		return
	}

	state := models.TLSCertsModel{
		EnvironmentID: types.StringValue(environmentID),
		Page:          types.Int32Value(int32(page)),
		PageSize:      types.Int32Value(int32(pageSize)),
		ItemCount:     types.Int32Value(int32(tlsCertsResponse.TotalItems)),
		Certificates:  []models.TLSCertModel{},
	}

	for _, cert := range tlsCertsResponse.Certificates {
		certState := models.TLSCertModel{
			ID:               types.StringValue(cert.ID),
			EnvironmentID:    types.StringValue(cert.EnvironmentID),
			PrimaryCert:      types.StringValue(cert.PrimaryCert),
			IntermediateCert: types.StringValue(cert.IntermediateCert),
			Expiration:       types.StringValue(cert.Expiration),
			Status:           types.StringValue(cert.Status),
			Generated:        types.BoolValue(cert.Generated),
			Serial:           types.StringValue(cert.Serial),
			CommonName:       types.StringValue(cert.CommonName),
			AlternativeNames: convertToListOfString(cert.AlternativeNames),
			ActivationError:  types.StringValue(cert.ActivationError),
			CreatedAt:        types.StringValue(cert.CreatedAt),
			UpdatedAt:        types.StringValue(cert.UpdatedAt),
		}

		state.Certificates = append(state.Certificates, certState)
	}

	diags = resp.State.Set(ctx, &state)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
}

func convertToListOfString(input []string) types.List {
	elements := make([]attr.Value, len(input)) // Change to attr.Value
	for i, v := range input {
		elements[i] = types.StringValue(v) // This is still correct
	}

	list, err := types.ListValue(types.StringType, elements)
	if err != nil {
		return types.List{}
	}

	return list
}
